# Generated by Django 5.1.5 on 2025-02-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Username',
        ),
    ]
