# Generated by Django 5.1.5 on 2025-02-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_username_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
